const regimes=['ABC/3TC/ATV-r','ABC/3TC/DTG','ABC/3TC/EFV','ABC/3TC/LPV-r','ABC/3TC/NVP','AZT/3TC/ABC','AZT/3TC/ATV-r','AZT/3TC/DTG','AZT/3TC/EFV','AZT/3TC/LPV-r','AZT/3TC/TDF','TDF/3TC/ATV-r','TDF/3TC/DTG','TDF/3TC/EFV','TDF/3TC/LPV-r'];
const truth=v=>[true,1,'1','t','true','Oui','oui'].includes(v);
function due(r){const s=String(r.derniere_dispensation||'').slice(0,10),n=Number(r.jours_dispenses);if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||!Number.isInteger(n)||n<=0)return null;const d=new Date(s+'T00:00:00Z');if(!Number.isFinite(+d)||d.toISOString().slice(0,10)!==s)return null;d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
function snapshot(reports,m,y){const map=new Map();for(const rep of reports.filter(x=>Number(x.annee)*100+Number(x.mois)<=y*100+m).sort((a,b)=>a.annee-b.annee||a.mois-b.mois))for(const r of rep.rows_json||[])map.set(String(r.patient_code),r);return [...map.values()];}
function issues(r,m,y){const a=[];if(!String(r.patient_code||'').trim())a.push('Code patient manquant');if(!['H','M','F'].includes(String(r.sexe||'').toUpperCase()))a.push('Sexe non renseigné');if(r.age==null||r.age==='')a.push('Âge non renseigné');if(!(Number(r.poids)>0))a.push('Poids non renseigné ou nul');if(!due(r))a.push('Date de dispensation ou durée manquante');const end=new Date(Date.UTC(y,m,0)).toISOString().slice(0,10);if(r.derniere_dispensation>end)a.push('Date postérieure au mois choisi');for(const [k,l] of [['type_vih','Type de VIH'],['ligne_therapeutique','Ligne thérapeutique'],['regime','Régime']])if(['','0','inconnu','non précisé','non'].includes(String(r[k]||'').toLowerCase().trim()))a.push(l+' à préciser');return a;}
function agenda(reports,m,y){const prior=snapshot(reports,m===1?12:m-1,m===1?y-1:y),now=reports.find(r=>Number(r.mois)===m&&Number(r.annee)===y)?.rows_json||[],map=new Map(),current=new Map(now.map(r=>[r.patient_code,r])),prefix=`${y}-${String(m).padStart(2,'0')}`;for(const r of [...prior,...now]){if(['deces','transfert_out','arret_tarv','perdu_vue'].some(k=>truth(r[k])))continue;const d=due(r);if(d?.startsWith(prefix)&&!map.has(r.patient_code))map.set(r.patient_code,{patient_code:r.patient_code,date_rendez_vous:d,statut:String(current.get(r.patient_code)?.derniere_dispensation||'').startsWith(prefix)?'Servi':'Attendu'});}return [...map.values()].sort((a,b)=>a.date_rendez_vous.localeCompare(b.date_rendez_vous)||a.patient_code.localeCompare(b.patient_code));}
function summary(reports,m,y,structure,status){
 const key=v=>String(v||'').toUpperCase().replaceAll(' ','').replaceAll('-','/'),allReg=[...regimes,'Autres'],rm=new Map(allReg.map(r=>[key(r),r]));
 const definitions={dispensations:{title:'Dispensations du mois',groups:{received:'ARV reçus au cours du mois',d1:'1 mois d’ARV',d3:'3 mois d’ARV',d6:'6 mois d’ARV',d245:'2, 4 ou 5 mois d’ARV',d6plus:'Plus de 6 mois d’ARV',aes:'Cas d’AES ou cas particulier',mobile:'Patients mobiles',outside:'Total patients non suivis dans le centre'}},mouvements:{title:'Évolution de la file active',groups:{previous:'File active du mois précédent',out:'Transférés Out',lost:'Perdus de vue, décédés et arrêts de traitement',new:'Nouvelles inclusions',in:'Transférés In',return:'Retour après interruption',changed:'Patients ayant changé de régime'}},active:{title:'File active du mois',groups:{active:'File active du mois',a1:'1 mois d’ARV',a3:'3 mois d’ARV',a6:'6 mois d’ARV',aother:'2, 4, 5 ou plus de 6 mois d’ARV',stable:'Patients stables',elsewhere:'Patients servis ailleurs'}}};
 const sections=Object.fromEntries(Object.entries(definitions).map(([k,d])=>[k,{...d,rows:allReg.map(regime=>({regime,groups:Object.fromEntries(Object.keys(d.groups).map(g=>[g,[0,0,0,0,0]]))}))}]));
 const add=(s,g,r)=>{const a=sections[s].rows[allReg.indexOf(rm.get(key(r.regime))||'Autres')].groups[g];a[4]++;const sex=String(r.sexe||'').toUpperCase();if(r.age!=null&&r.age!==''&&['M','H','F'].includes(sex))a[(Number(r.age)>=15?0:2)+(sex==='F'?1:0)]++;};
 const active=r=>truth(r.file_active)&&!['deces','transfert_out','arret_tarv','perdu_vue'].some(k=>truth(r[k]));
 const duration=r=>{const n=Number(r.jours_dispenses);return n===30?'1':n===90?'3':n===180?'6':[60,120,150].includes(n)?'245':n>180?'6plus':null;};
 const prev=snapshot(reports,m===1?12:m-1,m===1?y-1:y),current=snapshot(reports,m,y),monthly=reports.find(r=>Number(r.mois)===m&&Number(r.annee)===y)?.rows_json||[],pm=new Map(prev.map(r=>[r.patient_code,r]));let unknown=0,other=0,aes=false,mobile=false;const prefix=`${y}-${String(m).padStart(2,'0')}`;
 for(const r of prev)if(active(r))add('mouvements','previous',r);
 for(const r of monthly){if(String(r.derniere_dispensation||'').startsWith(prefix)){add('dispensations','received',r);const d=duration(r);if(d)add('dispensations','d'+d,r);else other++;}for(const [k,g] of Object.entries({transfert_out:'out',nouvelle_inclusion:'new',transfert_in:'in',retour_soins:'return'}))if(truth(r[k]))add('mouvements',g,r);if(['perdu_vue','deces','arret_tarv'].some(k=>truth(r[k])))add('mouvements','lost',r);if(pm.has(r.patient_code)&&key(pm.get(r.patient_code).regime)!==key(r.regime))add('mouvements','changed',r);aes ||=r.cas_aes!=null;mobile ||=r.patient_mobile!=null;if(truth(r.cas_aes))add('dispensations','aes',r);if(truth(r.patient_mobile))add('dispensations','mobile',r);if(truth(r.cas_aes)||truth(r.patient_mobile))add('dispensations','outside',r);}
 for(const r of current){if(!active(r))continue;add('active','active',r);const d=duration(r);if(['1','3','6'].includes(d))add('active','a'+d,r);else if(d)add('active','aother',r);if(String(r.stable||'').toLowerCase()==='oui')add('active','stable',r);if(truth(r.servi_ailleurs))add('active','elsewhere',r);if(r.age==null||!['H','M','F'].includes(String(r.sexe||'').toUpperCase()))unknown++;}
 for(const section of Object.values(sections)){const totals=Object.fromEntries(Object.keys(section.groups).map(g=>[g,[0,0,0,0,0]]));for(const r of section.rows)for(const [g,vs] of Object.entries(r.groups))vs.forEach((n,i)=>totals[g][i]+=n);section.rows.push({regime:'TOTAL',groups:totals});}
 for(const r of sections.dispensations.rows){if(!aes)r.groups.aes=null;if(!mobile)r.groups.mobile=null;if(!aes||!mobile)r.groups.outside=null;}
 return{meta:{structure:structure.nom_entite,code_dhis2:structure.code_dhis2,mois:m,annee:y,statut:status},adult_age:15,sections,notes:['Adultes : 15 ans et plus. Enfants : moins de 15 ans.','30 jours = 1 mois ; 90 jours = 3 mois ; 180 jours = 6 mois.','Les absences ne sont pas automatiquement classées comme pertes de vue.','n.r. : donnée non renseignée.'],unclassified_age_sex:unknown,unclassified_duration:other};
}
module.exports={truth,due,snapshot,issues,agenda,summary};
