(function(){
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const api=async(path,body,method='POST')=>{const r=await fetch('/api/clinical/'+path,{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+window.clinicalToken},body:method==='GET'?undefined:JSON.stringify(body)});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Opération impossible.');return j;};
 window.clinicalStatuses=async(m,y)=>{if(!window.user||user.role!=='ADMIN')return{};try{const j=await api('statuses?mois='+m+'&annee='+y,{},'GET');return Object.fromEntries(j.rows.map(x=>[x.code_dhis2,x]));}catch(_){return{};}};
 window.clinicalStatusCell=(s,map,m,y)=>{const x=map[s.code_dhis2];return '<td>'+(!x?'Non saisie':x.status==='VALIDE'?'Validée':'Brouillon')+'</td>';};
 let state={};
 const selected=()=>document.getElementById('clinical-structure')?.value;
 async function refresh(){const code=selected(),m=Number(document.getElementById('clinical-month').value),y=Number(document.getElementById('clinical-year').value);if(!code)return;const box=document.getElementById('clinical-result');box.innerHTML='Chargement…';try{state=await api('view',{code_dhis2:code,mois:m,annee:y});const agenda=state.agenda.map(x=>`<tr><td>${esc(x.patient_code)}</td><td>${esc(x.date_rendez_vous)}</td><td>${esc(x.statut)}</td></tr>`).join('')||'<tr><td colspan="3">Aucun rendez-vous.</td></tr>';const problems=state.issues.map((x,i)=>`<tr><td>${esc(x.row.patient_code)}</td><td>${esc(x.reasons.join(' ; '))}</td><td><button onclick="clinicalEdit(${i})">Modifier</button></td></tr>`).join('')||'<tr><td colspan="3">Aucun problème.</td></tr>';box.innerHTML=`<p><b>${esc(state.structure.nom_entite)}</b> — ${esc(state.status)}</p><div class="clinical-quick"><label>Code patient <input id="clinical-code"></label><label>Date de prise <input id="clinical-date" type="date"></label><label>Jours de traitement <input id="clinical-days" type="number" min="1"></label><button onclick="clinicalVisit()">Enregistrer la prise</button></div><h3>Rendez-vous du mois</h3><table><thead><tr><th>Patient</th><th>Rendez-vous</th><th>Statut</th></tr></thead><tbody>${agenda}</tbody></table><h3>Patients à corriger</h3><table><thead><tr><th>Patient</th><th>Raison</th><th></th></tr></thead><tbody>${problems}</tbody></table><div id="clinical-summary">${window.renderClinicalSummary?renderClinicalSummary(state.summary):''}</div>${state.rows.length?'<button onclick="clinicalValidate()">Valider la file active</button>':''}`;}catch(e){box.innerHTML='<p class="error">'+esc(e.message)+'</p>';}}
 window.clinicalVisit=async()=>{try{const b={code_dhis2:selected(),mois:+document.getElementById('clinical-month').value,annee:+document.getElementById('clinical-year').value,revision:state.revision,patient_code:document.getElementById('clinical-code').value.trim(),derniere_dispensation:document.getElementById('clinical-date').value,jours_dispenses:+document.getElementById('clinical-days').value};await api('visit',b);await refresh();}catch(e){alert(e.message);}};
 window.clinicalEdit=async i=>{const row=state.issues[i].row,code=prompt('Code patient',row.patient_code);if(code===null)return;const age=prompt('Âge',row.age??'');if(age===null)return;const weight=prompt('Poids (kg)',row.poids??'');if(weight===null)return;try{await api('edit',{code_dhis2:selected(),mois:+document.getElementById('clinical-month').value,annee:+document.getElementById('clinical-year').value,revision:state.revision,original_code:row.patient_code,row:{patient_code:code,age,poids:weight}});await refresh();}catch(e){alert(e.message);}};
 window.clinicalValidate=async()=>{try{await api('validate',{code_dhis2:selected(),mois:+document.getElementById('clinical-month').value,annee:+document.getElementById('clinical-year').value,revision:state.revision});await refresh();}catch(e){alert(e.message);}};
 window.clinicalHome=async(actor,m,y)=>{const host=document.getElementById('clinical-home');if(!host)return;const choices=(window.clinicalStructures||[]).filter(x=>actor.role==='ADMIN'?x.role==='USER':x.code_dhis2===actor.code_dhis2);host.innerHTML=`<section class="clinical-card"><h2>File active</h2><p>Rendez-vous, corrections et synthèse de la file active.</p><label>Structure <select id="clinical-structure">${choices.map(x=>`<option value="${esc(x.code_dhis2)}">${esc(x.nom_entite)}</option>`).join('')}</select></label> <label>Mois <input id="clinical-month" type="number" min="1" max="12" value="${esc(m)}"></label> <label>Année <input id="clinical-year" type="number" value="${esc(y)}"></label> <button id="clinical-load">Afficher</button><div id="clinical-result"></div></section>`;document.getElementById('clinical-load').onclick=refresh;await refresh();};
})();
