(function(){
 const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),F=window.ClinicalFields;
 const api=async(path,body,method='POST')=>{const r=await fetch('/api/clinical/'+path,{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+window.clinicalToken},body:method==='GET'?undefined:JSON.stringify(body)});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Opération impossible.');return j;};
 window.clinicalStatuses=async(m,y)=>{if(typeof user==='undefined'||user?.role!=='ADMIN')return{};const j=await api(`statuses?mois=${m}&annee=${y}`,{},'GET');return Object.fromEntries(j.rows.map(x=>[x.code_dhis2,x]));};
 window.clinicalStatusCell=(s,map)=>'<td>'+(!s.code_dhis2?'—':!map[s.code_dhis2]?'Non saisie':map[s.code_dhis2].status==='VALIDE'?'Validée':'Brouillon')+'</td>';
 let state=null,sequence=0,page=0;
 const context=()=>({code_dhis2:$('clinical-structure').value,mois:+$('clinical-month').value,annee:+$('clinical-year').value});
 function bindEdits(host){host.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));}
 const table=(headers,body)=>`<div class="table-scroll"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${body}</tbody></table></div>`;
 const editButton=code=>`<button type="button" data-edit="${esc(code)}">Modifier / prise</button>`;
 async function refresh(){
  const seq=++sequence,c=context(),box=$('clinical-result');state=null;
  if(!c.code_dhis2){box.innerHTML='<p>Le district doit renseigner le code DHIS2 de cette structure.</p>';return;}
  box.innerHTML='<p>Chargement de la file active…</p>';
  try{const data=await api('view',c);if(seq!==sequence)return;state={...data,context:c};page=0;render();}catch(e){if(seq===sequence)box.innerHTML=`<p role="alert" class="portal-error">${esc(e.message)}</p>`;}
 }
 function render(){
  const kpis=[[state.patients.filter(F.active).length,'Patients actifs'],[state.agenda.filter(r=>r.statut==='Attendu').length,'Rendez-vous attendus'],[state.rows.length,'Fiches du mois'],[state.issues.length,'Fiches à compléter']];
  $('clinical-result').innerHTML=`<div class="section-heading"><div><h3>${esc(state.structure.nom_entite)}</h3><p>${esc(state.status)} · ${state.context.mois}/${state.context.annee}</p></div><button id="clinical-new" class="primary-action">+ Nouvelle inclusion</button></div><p id="clinical-notice" role="status"></p><div class="portal-kpis">${kpis.map(([n,l])=>`<article><strong>${n}</strong><span>${l}</span></article>`).join('')}</div>
  <div class="clinical-tabs" role="tablist" aria-label="File active">${[['appointments','Rendez-vous'],['patients','Patients'],['pivot','Tableau croisé'],['summary','Synthèse et validation']].map(([k,l])=>`<button role="tab" aria-selected="${k==='appointments'}" data-tab="${k}">${l}</button>`).join('')}</div>
  <section id="clinical-tab-appointments" role="tabpanel"><div class="section-heading"><h3>Rendez-vous du mois</h3><label>Afficher<select id="appointment-filter"><option value="">Tous</option><option>Attendu</option><option>Servi</option></select></label></div><div id="appointment-table"></div></section>
  <section id="clinical-tab-patients" role="tabpanel" hidden><div class="section-heading"><h3>Fiches patients</h3><label>Rechercher un code<input id="clinical-search" type="search" placeholder="Code patient"></label></div><div id="patient-table"></div><div class="pagination"><button id="patients-prev">Précédent</button><span id="patients-page"></span><button id="patients-next">Suivant</button></div></section>
  <section id="clinical-tab-pivot" role="tabpanel" hidden><h3>Composer le tableau de file active</h3><p>Combinez les critères en lignes et en colonnes. Seules les combinaisons présentes apparaissent.</p><div class="pivot-controls"><fieldset><legend>Critères en lignes</legend>${Object.entries(F.dimensions).map(([k,l])=>`<label><input type="checkbox" name="pivot-row" value="${k}" ${k==='regime'?'checked':''}>${l}</label>`).join('')}</fieldset><label>Colonnes<select id="pivot-column">${Object.entries(F.dimensions).map(([k,l])=>`<option value="${k}" ${k==='sexe'?'selected':''}>${l}</option>`).join('')}</select></label><label>Population<select id="pivot-population"><option value="active">File active</option><option value="all">Tous les patients connus</option><option value="monthly">Fiches du mois</option></select></label><label>Tranche d’âge<select id="pivot-age"><option value="">Toutes</option><option>Enfants (&lt; 15 ans)</option><option>Adultes (≥ 15 ans)</option><option>Non renseigné</option></select></label><label>Sexe<select id="pivot-sex"><option value="">Tous</option><option>Masculin</option><option>Féminin</option><option>Non renseigné</option></select></label></div><div class="table-scroll" id="pivot-table" aria-live="polite"></div></section>
  <section id="clinical-tab-summary" role="tabpanel" hidden><h3>Synthèse mensuelle</h3><div class="table-scroll">${window.renderClinicalSummary?renderClinicalSummary(state.summary):''}</div><h3>Fiches à compléter</h3>${table(['Code patient','Points à compléter','Action'],state.issues.map(x=>`<tr><td>${esc(x.row.patient_code)}</td><td>${esc(x.reasons.join(' ; '))}</td><td>${editButton(x.row.patient_code)}</td></tr>`).join('')||'<tr><td colspan="3">Aucune fiche signalée.</td></tr>')}<button id="clinical-validate" class="primary-action" ${!state.rows.length||state.issues.length?'disabled':''}>Valider la file active du mois</button><p class="muted">Toute modification remet le rapport en brouillon.</p></section>
  <dialog id="patient-dialog"><form id="patient-form"><div class="section-heading"><h2 id="patient-title"></h2><button type="button" id="patient-close">Fermer</button></div><p id="patient-context"></p><div id="patient-fields" class="patient-fields"></div><p id="patient-error" class="portal-error" role="alert"></p><div class="form-actions"><button type="button" id="patient-cancel">Annuler</button><button type="submit" id="patient-save" class="primary-action">Enregistrer</button></div></form></dialog>`;
  document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.setAttribute('aria-selected',String(x===b)));for(const k of ['appointments','patients','pivot','summary'])$('clinical-tab-'+k).hidden=k!==b.dataset.tab;});
  $('clinical-new').onclick=()=>edit(null);$('appointment-filter').onchange=appointments;
  $('clinical-search').oninput=()=>{page=0;patientList();};$('patients-prev').onclick=()=>{page--;patientList();};$('patients-next').onclick=()=>{page++;patientList();};
  document.querySelectorAll('.pivot-controls input,.pivot-controls select').forEach(el=>el.onchange=pivot);
  $('clinical-validate').onclick=validate;bindEdits($('clinical-tab-summary'));appointments();patientList();pivot();
 }
 function appointments(){const filter=$('appointment-filter').value,rows=state.agenda.filter(r=>!filter||r.statut===filter),host=$('appointment-table');host.innerHTML=table(['Code patient','Rendez-vous','Statut','Action'],rows.map(r=>`<tr><td>${esc(r.patient_code)}</td><td>${esc(r.date_rendez_vous)}</td><td><span class="pill ${r.statut==='Servi'?'pill-ok':'pill-wait'}">${esc(r.statut)}</span></td><td>${editButton(r.patient_code)}</td></tr>`).join('')||'<tr><td colspan="4">Aucun rendez-vous pour ce filtre.</td></tr>');bindEdits(host);}
 function patientList(){const q=$('clinical-search').value.toLocaleLowerCase('fr'),rows=state.patients.filter(r=>String(r.patient_code).toLocaleLowerCase('fr').includes(q)).sort((a,b)=>a.patient_code.localeCompare(b.patient_code,'fr'));page=Math.max(0,Math.min(page,Math.max(0,Math.ceil(rows.length/50)-1)));const host=$('patient-table');host.innerHTML=table(['Code patient','Sexe','Âge','Régime','Statut','Action'],rows.slice(page*50,page*50+50).map(r=>`<tr><td>${esc(r.patient_code)}</td><td>${esc(r.sexe||'—')}</td><td>${esc(r.age??'—')}</td><td>${esc(r.regime||'—')}</td><td>${esc(F.status(r))}</td><td>${editButton(r.patient_code)}</td></tr>`).join('')||'<tr><td colspan="6">Aucun patient.</td></tr>');$('patients-page').textContent=`${rows.length} patients · page ${page+1}/${Math.max(1,Math.ceil(rows.length/50))}`;$('patients-prev').disabled=page===0;$('patients-next').disabled=(page+1)*50>=rows.length;bindEdits(host);}
 function pivot(){
  const col=$('pivot-column').value;document.querySelectorAll('[name="pivot-row"]').forEach(x=>{x.disabled=x.value===col;if(x.disabled)x.checked=false;});
  let keys=[...document.querySelectorAll('[name="pivot-row"]:checked')].map(x=>x.value);if(!keys.length){const first=document.querySelector('[name="pivot-row"]:not(:disabled)');first.checked=true;keys=[first.value];}
  const pop=$('pivot-population').value,age=$('pivot-age').value,sex=$('pivot-sex').value,rows=(pop==='monthly'?state.rows:state.patients).filter(r=>(pop!=='active'||F.active(r))&&(!age||F.dimension(r,'age_group')===age)&&(!sex||F.dimension(r,'sexe')===sex));
  const p=F.pivot(rows,keys,col),totals=Object.fromEntries(p.columns.map(c=>[c,0]));for(const r of p.rows)for(const c of p.columns)totals[c]+=r.counts[c]||0;
  $('pivot-table').innerHTML=`<table><caption>${p.total} patients · Colonnes : ${esc(F.dimensions[col])}</caption><thead><tr>${p.keys.map(k=>`<th>${F.dimensions[k]}</th>`).join('')}${p.columns.map(c=>`<th>${esc(c)}</th>`).join('')}<th>Total</th></tr></thead><tbody>${p.rows.map(r=>`<tr>${r.labels.map(l=>`<td>${esc(l)}</td>`).join('')}${p.columns.map(c=>`<td>${r.counts[c]||0}</td>`).join('')}<td><b>${r.total}</b></td></tr>`).join('')||`<tr><td colspan="${p.keys.length+p.columns.length+1}">Aucune combinaison pour ces filtres.</td></tr>`}</tbody><tfoot><tr><th colspan="${p.keys.length}">Total</th>${p.columns.map(c=>`<td>${totals[c]}</td>`).join('')}<td>${p.total}</td></tr></tfoot></table>`;
 }
 function edit(code){
  const isNew=code===null,old=isNew?null:state.patients.find(r=>r.patient_code===code);if(!isNew&&!old)return;
  const baseline={...old};if(old&&!state.rows.some(r=>r.patient_code===code))for(const k of ['nouvelle_inclusion','transfert_in','retour_soins'])baseline[k]='0';
  const forced=['nouvelle_inclusion','file_active','transfert_in','retour_soins','transfert_out','deces','arret_tarv','perdu_vue'],required=['patient_code','sexe','age','poids','type_vih','ligne_therapeutique','regime','derniere_dispensation','jours_dispenses'];
  $('patient-title').textContent=isNew?'Nouvelle inclusion':'Modifier la fiche patient';$('patient-context').textContent=`${state.structure.nom_entite} · ${state.context.mois}/${state.context.annee}${isNew?' · Ajout à la file active':''}`;
  $('patient-fields').innerHTML=Object.entries(F.fields).filter(([key])=>!isNew||!forced.includes(key)).map(([key,[label,type]])=>{
   const val=baseline[key]??'',need=isNew&&required.includes(key)?'required':'',v=type==='bool'?(val===''?'':F.truth(val)?'1':'0'):String(val);let input;
   if(type==='choice'||type==='bool'){
    const opts=type==='bool'?[{value:'1',label:'Oui'},{value:'0',label:'Non'}]:(state.options[key]||[]).filter(o=>o.active||String(o.value)===v);
    if(v&&!opts.some(o=>String(o.value)===v))opts.push({value:v,label:v});
    input=`<select name="${key}" ${need}><option value="">Non renseigné</option>${opts.map(o=>`<option value="${esc(o.value)}" ${String(o.value)===v?'selected':''}>${esc(o.label||o.value)}</option>`).join('')}</select>`;
   }else input=`<input name="${key}" type="${type==='date'?'date':type==='text'?'text':'number'}" ${type==='text'?'maxlength="150"':type==='date'?`max="${new Date(Date.UTC(state.context.annee,state.context.mois,0)).toISOString().slice(0,10)}"`:`min="${type==='integer'?1:0}" step="${type==='integer'?1:'any'}"`} value="${esc(v)}" ${key==='patient_code'&&!isNew?'readonly':''} ${need}>`;
   return `<label>${label}${need?' *':''}${input}</label>`;
  }).join('');
  $('patient-error').textContent='';const dialog=$('patient-dialog');$('patient-close').onclick=$('patient-cancel').onclick=()=>dialog.close();const c={...state.context,revision:state.revision};
  $('patient-form').onsubmit=async e=>{e.preventDefault();const save=$('patient-save');save.disabled=true;$('patient-error').textContent='';try{const row=Object.fromEntries(new FormData(e.currentTarget));await api(isNew?'create':'edit',{...c,original_code:code,row});dialog.close();await refresh();if(state)$('clinical-notice').textContent=isNew?'Nouvelle inclusion enregistrée. Le rapport est en brouillon.':'Fiche enregistrée. Le rapport est en brouillon.';}catch(error){$('patient-error').textContent=error.message;}finally{save.disabled=false;}};dialog.showModal();
 }
 async function validate(){const button=$('clinical-validate');button.disabled=true;try{await api('validate',{...state.context,revision:state.revision});await refresh();if(state)$('clinical-notice').textContent='File active du mois validée.';}catch(e){$('clinical-notice').textContent=e.message;button.disabled=false;}}
 window.clinicalHome=async(actor,m,y)=>{
  const host=$('clinical-home');for(const id of ['agent-home','district-zone','saisie-zone'])$(id).classList.add('no-disp');host.classList.remove('no-disp');
  const choices=(window.clinicalStructures||[]).filter(x=>actor.role==='ADMIN'?x.role==='USER'&&x.code_dhis2:x.id===actor.id);
  host.innerHTML=`<section class="clinical-card"><h2>File active</h2><p>Suivi des rendez-vous, fiches patients et nouvelles inclusions.</p><div class="portal-filters"><label>Structure<select id="clinical-structure" ${actor.role==='ADMIN'?'':'disabled'}>${choices.map(x=>`<option value="${esc(x.code_dhis2||'')}">${esc(x.nom_entite)}</option>`).join('')}</select></label><label>Mois<input id="clinical-month" type="number" min="1" max="12" value="${esc(m)}"></label><label>Année<input id="clinical-year" type="number" min="2020" max="2100" value="${esc(y)}"></label><button id="clinical-load">Actualiser</button></div><div id="clinical-result"></div></section>`;
  $('clinical-load').onclick=refresh;for(const id of ['clinical-structure','clinical-month','clinical-year'])$(id).onchange=refresh;await refresh();
 };
})();
